/**
 * AZMA OS – Al-Wateen Assistant
 * File: constants.ts
 *
 * System-wide constants for the Al-Wateen operating intelligence.
 */

export const ASSISTANT_CONFIG = {
  INIT_TIMEOUT_MS: 30000,
  HEALTH_CHECK_INTERVAL_MS: 5000,
  MONITORING_SNAPSHOT_INTERVAL_MS: 10000,
  RECOVERY_RETRY_ATTEMPTS: 3,
  RECOVERY_RETRY_DELAY_MS: 2000,
  TELEMETRY_BATCH_SIZE: 100,
  TELEMETRY_FLUSH_INTERVAL_MS: 30000,
  NOTIFICATION_RETENTION_DAYS: 7,
  REPORT_GENERATION_INTERVAL_MS: 3600000,
  MAX_CONCURRENT_REPAIRS: 5,
  PROVIDER_HEALTH_CHECK_INTERVAL_MS: 10000,
  ALERT_RETENTION_DAYS: 30,
  EVENT_RETENTION_DAYS: 7
} as const;

export const COMPONENT_TYPES = {
  CHAMBER: 'CHAMBER',
  AGENT: 'AGENT',
  SERVICE: 'SERVICE',
  PROVIDER: 'PROVIDER',
  GATEWAY: 'GATEWAY'
} as const;

export const RECOVERY_PRIORITIES = {
  LOW: 0,
  MEDIUM: 1,
  HIGH: 2,
  CRITICAL: 3
} as const;

export const ALERT_RETENTION_POLICIES = {
  INFO: 3600000,
  WARNING: 86400000,
  ERROR: 604800000,
  CRITICAL: 2592000000
} as const;

export const HEALTH_THRESHOLD = {
  HEALTHY: 0.95,
  WARNING: 0.80,
  CRITICAL: 0.50
} as const;
