/**
 * AZMA OS - Phase 7: Bab Al-Wusul (The Omni-Gateway & API Perimeter)
 * File: src/gateway/bab-al-wusul/gateway-topology-contracts.ts
 * * Gateway Health & Topology Contracts.
 * Establishes the constitutional observability structures for Bab Al-Wusul.
 * Provides read-only visibility into gateway health, registered routes, 
 * and bootstrap integrity without exposing execution logic.
 */

// ==========================================
// 1. GATEWAY STATE CONTRACTS
// ==========================================

export enum GatewayOperationalState {
  BOOTSTRAPPING = 'BOOTSTRAPPING',
  ONLINE = 'ONLINE',
  DEGRADED = 'DEGRADED',     // Operating, but experiencing high latency or partial handler failures
  MAINTENANCE = 'MAINTENANCE', // Deliberately rejecting non-admin traffic
  OFFLINE = 'OFFLINE'
}

export interface GatewayHealthMetrics {
  readonly uptimeSeconds: number;
  readonly activeRequests: number;
  readonly memoryUsageBytes?: number;
  readonly perimeterRejections: number; // Tracks how many requests failed the Zero-Trust check
}

// ==========================================
// 2. TOPOLOGY & BOOTSTRAP CONTRACTS
// ==========================================

/**
 * Diagnostic representation of a single registered internal route.
 */
export interface RouteTopologyEntry {
  readonly routePath: string;
  readonly isMounted: boolean;
  readonly handlerType?: string; // Optional metadata for debugging (e.g., 'QiyamahMaterializationHandler')
}

/**
 * The definitive map of all capabilities currently accessible through Bab Al-Wusul.
 */
export interface GatewayTopologyReport {
  readonly totalRegisteredRoutes: number;
  readonly routes: RouteTopologyEntry[];
  readonly missingRoutes: string[]; // Routes defined in the Registry but lacking a mounted handler
}

/**
 * The final report generated by the GatewayBootstrapper upon initialization.
 * Verifies that all mandatory constitutional components are active.
 */
export interface GatewayBootstrapVerification {
  readonly bootTimestampMs: number;
  readonly isPerimeterEnforcerActive: boolean;
  readonly isOmniRouterActive: boolean;
  readonly topologyReport: GatewayTopologyReport;
  readonly verifiedTraceId: string; // The genesis trace ID representing the boot event
}

// ==========================================
// 3. MASTER OBSERVABILITY SNAPSHOT
// ==========================================

/**
 * The complete diagnostic snapshot of Bab Al-Wusul.
 * Emitted to the Operation Ledger or requested by system administrators.
 */
export interface GatewayObservabilitySnapshot {
  readonly gatewayId: string;
  readonly state: GatewayOperationalState;
  readonly health: GatewayHealthMetrics;
  readonly topology: GatewayTopologyReport;
  readonly snapshotTimestampMs: number;
}